name: Crocker Design
favicon: null
layout_spectrum: 0.7069134141784161
typography_spectrum: 0.4217749198433012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.16721976408734918
  lightness: 0.4693892220966518
  saturation: 0.9471444254741073
  rhythmicContrast: 0.2850379233714193
purpose: []
