name: Crocker Design
favicon: null
layout_spectrum: 0.99581
typography_spectrum: 0.74288
title: 'Christian Crocker Design & Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161b21'
    - '#685956'
    - '#98a4a2'
    - '#308c98'
    - '#0a5b81'
  brandStrength: 0.16721976408734918
  lightness: 0.4693892220966518
  saturation: 0.9471444254741073
  rhythmicContrast: 0.2850379233714193
purpose: []
